---
- include_tasks: is_systemd.yml

# Variable configuration.
- include_tasks: variables.yml

- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - debian-keyring
      - debian-archive-keyring
      - apt-transport-https
      - gnupg2
      - curl
    state: present

- name: Ensure /etc/apt/keyrings exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: "{{ docker_apt_gpg_key }}"
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker repository to Apt sources
  ansible.builtin.apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: true
    filename: docker

- name: Install Docker CLI.
  apt:
    name: "{{ docker_packages }}"
    state: present



- include_tasks: docker-users.yml
  when: docker_users | length > 0
