---
- include_tasks: is_systemd.yml

# Variable configuration.
- include_tasks: variables.yml

- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - debian-keyring
      - debian-archive-keyring
      - apt-transport-https
      - gnupg2
      - curl
    state: present

- name: Add Docker apt key.
  become: true
  become_user: root
  apt_key:
    url: "{{ docker_apt_gpg_key }}"
    state: present

- name: Add Docker repository.
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: true

- name: Install Docker CLI.
  apt:
    name: "{{ docker_packages }}"
    state: present

- name: Install Docker Compose SDK for python.
  become: true
  become_user: root
  pip:
    name:
      - docker-compose
    state: present
    executable: pip3

- include_tasks: docker-compose.yml
  when: docker_install_compose | bool

- include_tasks: docker-users.yml
  when: docker_users | length > 0
