---
# Variable configuration.
- name: Check os and version
  debug:
    msg: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('-')[0].split('.')[0] }}"

- name: Include OS-specific variables (Debian).
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('-')[0].split('.')[0] }}.yml"
  when: ansible_os_family == 'Debian'

- name: Define docker_packages.
  set_fact:
    docker_packages: "{{ __docker_packages | list }}"
  when: docker_packages is not defined

- name: Define docker_version.
  set_fact:
    docker_version: "{{ __docker_version }}"
  when: docker_version is not defined

- name: Define docker_apt_repository
  set_fact:
    docker_apt_repository: "{{ __docker_apt_repository }}"
  when: docker_apt_repository is not defined

- name: Define docker_bin_path.
  set_fact:
    docker_bin_path: "{{ __docker_bin_path }}"
  when: docker_bin_path is not defined

- name: Define docker_config_path.
  set_fact:
    docker_config_path: "{{ __docker_config_path }}"
  when: docker_config_path is not defined
